# Basic Information 
title: Yazhou Zhu
position: PhD Student
affiliation: Nanjing University of Science and Technology
email: zyz_nj(at)njust.edu.cn

keywords: Medical Image Analysis

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=xfRJtTwAAAAJ&hl=en
# cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/YazhouZhu19
# linkedin: https://www.linkedin.com/
# twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/IMG_1251.jpeg
favicon: ./assets/img/IMG_1251.jpeg
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true


